# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import asr_service_pb2 as asr__service__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in asr_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FasterWhisperASRStub:
    """ASR gRPC 服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamRecognize = channel.stream_stream(
                '/asr.FasterWhisperASR/StreamRecognize',
                request_serializer=asr__service__pb2.AudioChunk.SerializeToString,
                response_deserializer=asr__service__pb2.AsrResult.FromString,
                _registered_method=True)
        self.RecognizeFile = channel.unary_unary(
                '/asr.FasterWhisperASR/RecognizeFile',
                request_serializer=asr__service__pb2.AudioFile.SerializeToString,
                response_deserializer=asr__service__pb2.RecognizeResult.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/asr.FasterWhisperASR/GetStatus',
                request_serializer=asr__service__pb2.StatusRequest.SerializeToString,
                response_deserializer=asr__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateSettings = channel.unary_unary(
                '/asr.FasterWhisperASR/UpdateSettings',
                request_serializer=asr__service__pb2.AsrSettings.SerializeToString,
                response_deserializer=asr__service__pb2.StatusResponse.FromString,
                _registered_method=True)


class FasterWhisperASRServicer:
    """ASR gRPC 服务定义
    """

    def StreamRecognize(self, request_iterator, context):
        """双向流式 RPC：客户端流式发送音频，服务端流式返回识别结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeFile(self, request, context):
        """非流式识别：上传完整音频文件，返回完整识别结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """获取服务状态（模型是否加载完成等）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSettings(self, request, context):
        """设置 ASR 参数（模型、VAD 等）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FasterWhisperASRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamRecognize': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamRecognize,
                    request_deserializer=asr__service__pb2.AudioChunk.FromString,
                    response_serializer=asr__service__pb2.AsrResult.SerializeToString,
            ),
            'RecognizeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFile,
                    request_deserializer=asr__service__pb2.AudioFile.FromString,
                    response_serializer=asr__service__pb2.RecognizeResult.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=asr__service__pb2.StatusRequest.FromString,
                    response_serializer=asr__service__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSettings,
                    request_deserializer=asr__service__pb2.AsrSettings.FromString,
                    response_serializer=asr__service__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asr.FasterWhisperASR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('asr.FasterWhisperASR', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FasterWhisperASR:
    """ASR gRPC 服务定义
    """

    @staticmethod
    def StreamRecognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/asr.FasterWhisperASR/StreamRecognize',
            asr__service__pb2.AudioChunk.SerializeToString,
            asr__service__pb2.AsrResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asr.FasterWhisperASR/RecognizeFile',
            asr__service__pb2.AudioFile.SerializeToString,
            asr__service__pb2.RecognizeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asr.FasterWhisperASR/GetStatus',
            asr__service__pb2.StatusRequest.SerializeToString,
            asr__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asr.FasterWhisperASR/UpdateSettings',
            asr__service__pb2.AsrSettings.SerializeToString,
            asr__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
